services:
  postgres:
    image: postgres:16
    container_name: classical_postgres
    environment:
      POSTGRES_USER: recommender
      POSTGRES_PASSWORD: recommender123
      POSTGRES_DB: classical
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
